name: pixi_examples
version: 0.1.4
author: Federico Omoto <federico.omoto@gmail.com>
description: Pixi examples ported to Dart.
homepage: https://github.com/FedeOmoto/pixi_examples
environment:
  sdk: '>=1.5.3 <1.7.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  dart_to_js_script_rewriter: '>=0.0.1+2 <0.0.2'
  pixi_dart: '>=0.1.68 <0.2.0'
transformers:
- dart_to_js_script_rewriter
