name: pixi_examples
version: 0.2.0
author: Federico Omoto <federico.omoto@gmail.com>
description: Pixi examples ported to Dart.
homepage: https://github.com/FedeOmoto/pixi_examples
environment:
  sdk: '>=1.5.8 <1.7.0'
dependencies:
  browser: '>=0.10.0+2 <0.12.0'
  dart_to_js_script_rewriter: '>=0.0.1+2 <0.0.3'
  pixi_dart: '>=0.2.0 <0.4.0'
transformers:
- dart_to_js_script_rewriter
